### ISSUE TITLE
Working on MacOS Mojave... but samplerate question

### ISSUE THREAD

**Issue by AletheianAlex** [OpenHantek/OpenHantek6022#23]
Firstly, thank you for this project.  It is working better than the stock software and vanilla OpenHantek.  Second, Just wanted to confirm that it is working fine on MacOS Mojave 10.14.6.  I did have a quick question about the samplerate.  It seems that the 48Ms/s option is not available in single channel mode.  Was that omitted because of stability?  I looked though the commits, and saw a note on the Jun 10 that seemed to indicate that is the reason

**Comment by Ho-Ro** [comment]
Hi AletheianAlex,

You're right, 48MS/s are above the capacity of a typical USB 2.0 connection (the 6022 can only use USB 2.0). Theoretically USB 2.0 can transfer 480 Mbit/s -> 60 MByte/s, but with protocol overhead and (more importantly) not having the USB capacity alone, only half the theoretical value can be used for user data (even if this already has some drop-outs / overflows). The 48 MS/s are purely Hantek's marketing, mainly due to the fact that the heart of the device, the Cypress EzUSB chip, offers this maximum speed. Maybe you're lucky enough to reach the 48 speed in a special PC configuration with just one USB port connected directly to the outside without a hub etc. 
So I decided quite early (https://github.com/OpenHantek/OpenHantek6022/commit/7f4718e5d398a95251b39a526626940db668a14d) to drop the distorted 48, I don't offer 30 automatically either - for fast time base settings the device will select 24 MS/s and the user will have to select 30 MS/s manually if needed.

Please also take a look at the huge thread from Down-Under, especially [this message](https://www.eevblog.com/forum/testgear/hantek-6022be-20mhz-usb-dso/msg661509/#msg661509).

Martin
