### ISSUE TITLE
Frequencybase value does not update in the UI

### ISSUE THREAD

**Issue by jsiddall** [OpenHantek/OpenHantek6022#330]
**Describe the bug**
The Frequencybase setting gets updated when the Timebase setting is changed, but the Frequencybase value is not updated in the UI.

**To Reproduce**
1. Start in demo mode
2. Enable a spectrum display
3. Change the timebase
4. The spectrum scale changes but the Frequencybase number remains the same.

**Expected behavior**
The Frequencybase number is updated when the spectrum scale changes

**Screenshots**

**Computer environment (please complete the following information):**
 - OpenHantek version: openhantek_20220731-b3afdec_amd64
 - OS: Linux
 -  Distribution, version: Ubuntu 20.04
 - Video hardware: nVidia
 - OpenGL version: OpenGL 4.5, Mesa 21.2.6
 
**Scope device (please complete the following information):**
 - Device: Demo mode
 - Probe setting: no probe
 - 
**Additional context**

**Comment by Ho-Ro** [comment]
@jsiddall 
> Start in demo mode
Enable a spectrum display
Change the timebase
The spectrum scale changes but the Frequencybase number remains the same.

Why should the frequency basis (the spectrum frequency scale per division) change?
Time and spectrum are two different ways of looking at the same physical phenomenon. Therefore, the scale can also be chosen independently within the context of the physical conditions - see the basics of the Fourier transform.
If you look at the same input signal with different time bases, the spectrum (the position and magnitude of the harmonics) remains the same, only the width of the lobes changes (due to the different duration of the sampling window: longer window -> narrower lobe. The shape of the lobes is the Fourier transform of the window function convolved with the real spectrum, if you were to sample a stationary signal infinitely long, there would be no limiting window function and the lobes would be infinitely narrow).
The only required influence of the sampling rate (which also depends on the time base) on the frequency base is that the maximum frequency base cannot be greater than sample rate/20 (due to Nyquist, since the maximum frequency in the spectrum cannot be greater than half the sample rate and since the frequency base is given per division and you have 10 horizontal divisions, the maximum frequency is therefore 10*frequencybase).
The other influence of the time base on the frequency display of the demo unit is that at slow sample rates < 100 kS/s, the frequency of the demo signal is also reduced, which can be seen in the frequency display at the bottom right. I chose this physical inaccuracy in order to obtain a usable signal shape even with slow time bases. With the real unit, of course, the input signal remains the same, even if the settings change.

Martin
