### ISSUE TITLE
Hantek 6254BD support

### ISSUE THREAD

**Issue by janschiefer** [OpenHantek/OpenHantek6022#359]
I'm currently running the shitty Hantek Windows software on a Vmware Virtual machine ( Windows 10 ) on Linux to use my Hantek 6254BD scope. If I try the Hantek software on Windows 11 the driver crashes the OS on USB connect.

Is there any realistic chance for support of higher end scopes on native Linux like Hantek6254BD (4 Channel 200MHz) in the foreseeable future?

I here anything someone can do to help?

**Comment by Ho-Ro** [comment]
> support of higher end scopes

Unfortunately this is not possible without big restructuring because I optimized the data flow with regards to the low end HW.
If you want to investigate further the legacy project [openhantek](https://github.com/OpenHantek/openhantek) could be a starting point, as well as my old branch [last_legacy_support](https://github.com/OpenHantek/OpenHantek6022/tree/last_legacy_support).
