### ISSUE TITLE
Displayed signal jumps up when sampling with 30MS/s

### ISSUE THREAD

**Issue by pedropedro** [OpenHantek/OpenHantek6022#63]
Hi Ho-Ro,

please see attached screenshot. Setting the sampling to anything (allowed) below 30MS/s yields
the calibration signal base (lowest peak value) displayed exactly at the CH1 level, i.e. -500mV in
this test. Just selecting the 30MS/s pushes the displayed signal up by ~ 50mV, so the signal base
lies at ~ -450mV. Just selecting any different sampling rate returns the signal base back to the
CH1 level ( -500mV). No other difference visible.

**Computer environment :**
 - OS: Xubuntu 19.09 amd64 on VirtualBox 6.1.4

**Scope device :**
 - Device Hantek 6022BE
 - Program top line OpenHantek6022 3.0.2 - FW0204
 - Input signal: calibration out 20 kHz
 - Probe setting: probe X1

![OH6022-3 0 2-FW0204 Samplerate](https://user-images.githubusercontent.com/2650935/76687059-c4810d80-6620-11ea-8128-728986d807b3.png)

**Comment by Ho-Ro** [comment]
The offset of the ADC changes when clocked with >= 30 MHz; the EEPROM of the Hantek6022 contains separate offset (as well as gain) [calibration values](https://github.com/Ho-Ro/Hantek6022API/blob/master/docs/README.md#eeprom) for slow sample rates < 30 MS/s and high sample rates >= 30 MS/s. 
Have you [calibrated](https://github.com/Ho-Ro/Hantek6022API/blob/master/README.md#create-calibration-values-for-openhantek) the scope recently? Due to the [brain-dead hardware](https://github.com/OpenHantek/OpenHantek6022/issues/45#issuecomment-579257234) of the Hantek scope the offset can drift over time.
OpenHantek uses the extended calibration values (created by the python calibration program) that allow to drop the offset to a sub-digit level.

**Comment by Ho-Ro** [comment]
I cannot follow up unless you provide some more info.

**Comment by pedropedro** [comment]
No, I did not calibrate the scope in my (current) Linux VM. I started first with a WinXP VM with the original Hantek software, where I tried the menu function Utility\Calibrate - no feedback from the software. But when I understand it right, that calibration (? when there was one at all) does not matter, OpenHantek in the new Linux VM "flashes" the scope at every boot from scratch.

**Comment by Ho-Ro** [comment]
The calibration values for the scope are stored permanently in the small EEPROM, while the firmware is "flashed" into the RAM on every start of the program. There is also the possibility to create a [calibration file](https://github.com/OpenHantek/OpenHantek6022/blob/master/openhantek/src/hantekdso/models/modelDSO6022.conf) that takes priority over the EEPROM calibration.

**Comment by pedropedro** [comment]
OK, my mistake.
After running *python3 calibrate.py -ce* the picture got better - sample rate != 30MS/s => rock stable 0V for the calibration signal (half the period ;-), for 30MS/s is the signal jump only ~ 5mV now, means 10x better.
Merci !
