### ISSUE TITLE
Help decoding a new device?

### ISSUE THREAD

**Issue by wolfallein** [OpenHantek/OpenHantek6022#85]
Hello,

I have a Hantek handheld oscilloscope.
It is a very good 70MHz scope but I would like to have a better PC software for it.

Hantek doesn't provide any SDK for this model, All the DLLs that their software uses has the same name as the 6062 ones, so I thought that the protocol could be the same as 6062 scopes and I tried using the headers of the 6062 DLLs that they provide with the DLLs for the 2d72. It didn't work. They changed more things.

Since they unlikely will launch an SDK for this model, I would like to know how I can start decoding the protocol and develop a library for it.

I think that most of the commands/protocols should be the same as other Hantek oscilloscopes, so maybe it is just a bypass that I have to pass to get it working. Where do you recommend to me to start?

**Comment by Ho-Ro** [comment]
> same as 6062 scopes

OpenHantek**6022** supports only the 6022 series (and mostly compatible devices), do you mean
*Hantek6022* or really *Hantek6062*? (which I don't know, quick search gave only *Owon SDS6062*)

OpenHantek6022 uses own free-open-source firmware (that nevertheless has a similar USB command structure as the Hantek FW). But the 6022 scopes are not more than an EzUSB chip plus an EEPROM plus an ADC chip, as can be seen on the last page of my [user manual](https://github.com/OpenHantek/OpenHantek6022/blob/master/docs/OpenHantek6022_User_Manual.pdf). This HW config limits the *theoretical* transfer rate to 48 MB/s (i.e. 48 MS/s when using only one channel), but due to USB protocol overhead only 30 MB/s can be transmitted what gives *usable* 30 MS/s (one channel) or 15 MS/s (two channels). 
The 2d72 on the other hand uses a different approach by sampling at a higher rate into a large local buffer and transmitting at lower rate over USB. 
You can check out the [long EEVBLOG thread](https://www.eevblog.com/forum/testgear/hantek-2c422c722d422d72/) for more info about your device. Also [sigrok](https://sigrok.org/wiki/Supported_hardware) could be a good starting point, even if your device is unsupported yet. 

HTH, Martin
