### ISSUE TITLE
time bases longer than 100 ms

### ISSUE THREAD

**Issue by bcrowell** [OpenHantek/OpenHantek6022#92]
Thanks for all your work on this software!

For my application, it would be really helpful to have time bases longer than 100 ms. From looking at videos of people using the Hantek Windows software, it looks like it goes up to 1 s. (My application is a physics lab where the students move a magnet near a coil and observe the induced EMF.)

**Comment by Ho-Ro** [comment]
Hello Ben,

It's already available in the source code, e.g. for the Hantek6022 model:
[`// define VERY_SLOW_SAMPLES to get timebase up to 1s/div at the expense of very slow reaction time (up to 20 s)`](https://github.com/OpenHantek/OpenHantek6022/blob/a883af2a1fe599b81231678c637dd2bf4a97f578/openhantek/src/hantekdso/models/modelDSO6022.cpp#L94)

    // define VERY_SLOW_SAMPLES to get timebase up to 1s/div at the expense of very slow reaction time (up to 20 s)
    //#define VERY_SLOW_SAMPLES
    specification.fixedSampleRates = {
    // samplerate, sampleId, downsampling
    #ifdef VERY_SLOW_SAMPLES
        {1e3, 110, 100}, // 100x downsampling from 100, 200, 500 kS/s!
        {2e3, 120, 100}, //
        {5e3, 150, 100}, //
    #endif

Uncomment the `//#define...` line, recompile and enjoy the slow sampling. 
I decided against always enabling this time setting because the GUI interaction becomes very unresponsive. It can take up to 20 seconds for a change to occur, so the screen will supposedly *freeze* if a user accidentally scrolls the timebase setting too far. 
Unfortunately, the software does not support any kind of *roll* mode, it scans a complete block of 20000 values (free-running), searches this block for a trigger point (Hantek has no hardware trigger) and finally displays 10000 samples of this block aligned to the trigger point (the other half is thrown away due to SW triggering to create a still image).
If you want to do long-time acquisition I would recommend the tools on my other repo [Hantek6022API](https://github.com/Ho-Ro/Hantek6022API), especially the [logger](https://github.com/Ho-Ro/Hantek6022API#use-the-device-as-a-data-logger).

HTH Martin
