### ISSUE TITLE
Real time option

### ISSUE THREAD

**Issue by spam-receiver** [OpenHantek/OpenHantek6022#99]
In real-time mode (when the trigger is disabled with a time base of 200 ms - 10 s), clear the screen from the previous graph every time before starting to draw a new graph. A button or a checkbox for quick on/off this feature. For example, an option in list of trigger modes: "None (from scratch)" or "None (with cleaning)".

**Comment by Ho-Ro** [comment]
Please check the latest 3.1.1-rc3 ...

**Comment by spam-receiver** [comment]
I really liked the scroll, but sometimes it’s easier to observe a static graph, so the previous option (without scroll) should also be available.

**Comment by Ho-Ro** [comment]
I don't like the wipe mode, because it throws away valuable information: e.g. you measure with 1 s/div (yielding 10 seconds on the screen) for 12 seconds, in *roll mode* you'll see the last 10 seconds, in *wipe mode* you'll see the last two seconds only and 8 useless seconds with an empty trace.
The most intuitive solution for displaying slow and time-unlimited processes is the appearance of a [chart recorder](https://en.wikipedia.org/wiki/Chart_recorder) - and if you want a defined starting point I've added the *refresh* button that clears the screen and starts the trace again from the left margin. see 4ffe158, available as the last [unstable](https://github.com/OpenHantek/OpenHantek6022/releases/tag/unstable).

**Comment by spam-receiver** [comment]
Well done! But what prevents the implementation of those two options? They do not interfere with other options, but only expand the possibilities of viewing waveforms in real time.

**Comment by spam-receiver** [comment]
The Refresh button should only be active in Scroll mode when the time base is 200 ms or higher.

**Comment by Ho-Ro** [comment]
> what prevents the implementation of those two options?

- Simple answer: I do not like it.
- More technical answer: The roll mode is already a dirty hack and each new mode adds more ugly code - and I have neither the time nor the desire to change these program structures from scratch.

(Have I already told that OpenHantek is based on code that is up to ten years old?)

**Comment by spam-receiver** [comment]
Sorry, I didn’t know that everything is so complicated. Thanks for all, that you do!

**Comment by Ho-Ro** [comment]
A question out of curiosity, what do you do with the program?

**Comment by spam-receiver** [comment]
Use it with Hantek DSO-6022BL in development of some bluetooth devices.

**Comment by Ho-Ro** [comment]
done with 3.1.1
